# Generated by Django 2.2.6 on 2019-10-16 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booked_seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
